backend:
  # local testing
  name: github
  repo: jef-lau/gatsby-netlify-tara

  # production
  # name: git-gateway

media_folder: static/assets
public_folder: /assets


collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/home.md"
        name: "home"
        label: "Home Page"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro text, name: intro, widget: text}
          - {label: Image, name: image, widget: image}
      - file: "content/media_gallery.md"
        name: "mediagallery"
        label: "Media Gallery"
        fields:
          - label: Media Gallery Images
            name: media_gallery_images
            widget: image
            media_library:
              config:
                multiple: true
      - file: "content/gallery.md"
        name: "gallery"
        label: "Photo Gallery"
        fields:
          - label: Gallery Images
            name: gallery_images
            widget: image
            media_library:
              config:
                multiple: true