backend:
  # local testing
  name: github
  repo: jef-lau/gatsby-netlify-tara

  # production
  # name: git-gateway

media_folder: static/assets
public_folder: /assets


collections:
  - name: "pages"
    label: "Pages"
    files:
      # - file: "content/home.md"
      #   name: "home"
      #   label: "Home Page"
      #   fields:
      #     - {label: Title, name: title, widget: string}
      #     - {label: Intro text, name: intro, widget: text}
      #     - {label: Image, name: image, widget: image}
      - file: "content/media_gallery.md"
        name: "media"
        label: "Media"
        fields:
          - { label: 'Text', name: 'body', widget: 'markdown' }
          - label: "Media Gallery"
            name: "mediaGalleryImages"
            widget: "list"
            field: {label: Image, name: image, widget: image}
      - file: "content/gallery.md"
        name: "gallery"
        label: "Gallery"
        fields:
          - { label: 'Text', name: 'body', widget: 'markdown' }
          - label: "Gallery Images"
            name: "galleryImages"
            widget: "list"
            field: {label: Image, name: image, widget: image}
      - file: "content/philanthropy.md"
        name: "philanthropy"
        label: "Philanthropy"
        fields:
          - { label: 'Text', name: 'body', widget: 'markdown' }
          - label: "Gallery Images"
            name: "galleryImages"
            widget: "list"
            field: {label: Image, name: image, widget: image}
      - file: "content/about.md"
        name: "about"
        label: "About"
        fields:
          - { label: 'Text', name: 'body', widget: 'markdown' }
          - label: "Gallery Images"
            name: "galleryImages"
            widget: "list"
            field: {label: Image, name: image, widget: image}
      - file: "content/publishinparadise.md"
        name: "publishinparadise"
        label: "Publish in Paradise"
        fields:
          - { label: 'Text', name: 'body', widget: 'markdown' }
          - label: "Gallery Images"
            name: "galleryImages"
            widget: "list"
            field: {label: Image, name: image, widget: image}